name: 'medicare_analytics'
version: '1.0.0'
config-version: 2

profile: 'medicare_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  medicare_analytics:
    # Bronze layer - external tables pointing to S3
    bronze:
      +materialized: external  # This tells dbt these are external tables
      +schema: bronze
    
    # Silver layer - cleaned and standardized data
    silver:
      +materialized: table
      +schema: silver